name: Build and Deploy Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Clean workspace
        run: |
          rm -rf ./node_modules
          rm -rf ./dist
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # Cambia a la versión de Ruby que necesites
      
      - name: Install Bundler
        run: gem install bundler
      
      - name: Install dependencies
        run: bundle install
      
      - name: Build site
        run: bundle exec jekyll build
